spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountingservice?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

logging:
  level:
    com.togo.accounting: DEBUG